Swedish lang
LinkCordApp/i18n pull request #2
Opened 2022-05-23 07:19 UTC by Miya25

Translated By RanveerSoni

2022-05-23 19:12 UTC, TheRealToxicDev commented on i1n8.config.js
>      'Italian'
Please correct the missing comma here.

2022-05-24 03:19 UTC, Miya25 commented on i1n8.config.js
>      'Italian'
oh sorry fixed

2022-05-24 04:13 UTC, SerenModz21 requested changes

2022-05-24 06:53 UTC, Miya25 commented
sorry i am done all the things thanks for letting me know!

2022-05-24 07:01 UTC, SerenModz21 requested changes

2022-05-24 07:01 UTC, SerenModz21 commented on i18n/locales/Swedish/Swedish.tsx
> +                        item_4: "Utveckla och implementera nya produkter, tjänster, funktioner och funktionalitet."",
```suggestion
                        item_4: "Utveckla och implementera nya produkter, tjänster, funktioner och funktionalitet.",
```

2022-05-24 07:10 UTC, SerenModz21 commented on i18n/locales/Swedish/Swedish.tsx
> +                        item_4: "Utveckla och implementera nya produkter, tjänster, funktioner och funktionalitet."",
once this one is resolved, please request a new review from me

2022-05-24 10:36 UTC, RizonFTW approved these changes
Seems fine to me now. Thank you.

2022-05-24 11:30 UTC, SerenModz21 approved these changes
looks good

2022-05-24 21:27 UTC, merged